### ISSUE TITLE
Intermittent empty bundle content with HTTP 200 response

### ISSUE THREAD

**Issue by GrantAdkins** [scott-xu/System.Web.Optimization.Less#21] opened 2014-06-30 05:36 UTC
Hi guys. I apologize in advance for the vagueness of this issue.

We have two sites using the latest version (1.3.2) deployed in production (not debug). The content of the less bundles is fine but occasionally (we're not sure of cause) the bundle content will be empty (returns with a 200 response) and the v parameter is empty: "skin?v=" so no hash value. I've poked around in your source and the System.Web.Optimization source and am at a loss as to how this could occur. I had thought it could be related to cache items being cleared (possibly due to low memory) but I think it unlikely.

If the cause was due to a less transform failing, I would expect it to always fail. The production sites are fine for long periods of time but then occasionally fail with this problem - a subsequent app pool recycle fixes it.

We think the timing correlates to when we upgraded from version 1.2.3. Have you encountered any similar reports? The frustrating thing is I can't reproduce this problem in any environments other than production so it's making trouble shooting really difficult. No exceptions are logged. I'm contemplating reverting back to version 1.2.3 but would prefer not to.

**Comment by chrilith** [comment] 2015-02-17 16:18
Hi, 

Any news on this issue? I have the same problem and don't really want to move to BundleTransformer as it depends on A LOT of other packages.

Thanks!

**Comment by rytmis** [comment] 2015-02-17 17:06
Ooh, @yetanotherchris, could you consider sharing the test bench and saving me the trouble? I've run into this in an environment where debugging was very hard, but having an easy repro would be a major help. I could take a swing at fixing this in dotless if you did.

**Comment by rytmis** [comment] 2015-02-18 18:13
So it turns out this is actually a duplicate of #17, and it's in fact really easy to reproduce: run your site with a startup url that has a query string parameter that dotless would consider invalid. E.g. ?a=b-c. If the very first request both hits a page that triggers LESS bundle generation and contains query string variables that dotless can't deal with, this happens. I'll add some further thoughts to dotless/dotless#418 where they belong.

**Comment by rytmis** [comment] 2015-03-09 12:49
Could you please try to upgrade to the latest dotless release and see if that fixes the issue for you?

**Comment by chrilith** [comment] 2015-03-09 16:20
I'll try do do this ASAP. Thanks!

**Comment by scott-xu** [comment] 2019-12-08 09:56
Please try the latest release. Thanks!

**Closed by scott-xu** 2019-12-08 09:56 UTC
